### ISSUE TITLE
ps5 RSS news feed

### ISSUE THREAD

**Issue by Mmorami** [palashsharma891/6.0001---MIT#3]
Hi @palashsharma891,
I wonder if you had the same problem as myself in ps5.
My code pass all of ps5_test tests, yet the tkinter will show an empty pop up no matter what triggers i apply.

I cloned your solution and tried to run it, but I got the same result. I tried to fix it in various ways but couldn't get it to work, hence i suspect that our code is not the problem, but something on the lines of a change in the yahoo/google news xml schemem (less likely), or a change in the tkinter library with taking into account that we probably used a more advanced version of python than the one used back when the course was enrolled (probably ~3.2).

what exactly is the bug that you experienced? is it the same as the bug i encountered?
BTW your code is very slick good job :+1:

**Comment by palashsharma891** [comment]
Hey @Mmorami,

Yes I had the same problem as you did. There is some bug in the yahoo part which I wasn't able to fully understand. So I removed that part and used only Google News and created a separate project.

Here is the link to the project: https://github.com/palashsharma891/RSS-Feed-Filter

Hope it helps!
