### ISSUE TITLE
Noob Question

### ISSUE THREAD

**Issue by Cabi06** [palashsharma891/6.0001---MIT#4]
Hello palashsharma, I am a complete noob so I apologize if this question sounds dumb, but on your answer for ps1c you have portion_saved = ??? which causes a syntax error. What do you have to change the ??? value to to make the program run? Thank you for your time :)

**Comment by palashsharma891** [comment]
Hi. I don't remember how I missed it but now the code is gone! The function calculate_savings_rate() will perform a binary search to find the optimal portion saved. So I guess the initial value of portion saved can be anything as it will be updated.
